fix: address issue #40, increase modal z-index from 300 to 400, so th…
AlaskaAirlines/AuroDesignTokens pull request #43
Opened 2021-03-13 01:59 UTC by BrentLabasan

… over tooltips

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #40 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

I increased the --auro-depth-modal value from 300 to 400, so that modals will appear over tooltips, which --auro-depth-tooltip is currently a value of 300.

This will fix situations like the picture below. This situation can be duplicated by clicking a non-saver fare in one matrix and then clicking a saver fare in the other matrix.
![image](https://user-images.githubusercontent.com/345019/111014745-16ef2a00-835a-11eb-8ccb-3844e421d786.png)

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-03-17 14:59 UTC, blackfalcon commented on src/depth.json
> +      "value": "{depth.400.value}",
I'd argue that `dialog` and `modal` are one in the same. So, please update both to be the same level and mark `modal` as deprecated. 

The primary token for use will be `dialog`. 

Dialog is a thing. Modal is a state.

2021-03-18 02:13 UTC, blackfalcon requested changes
See other notes about modal and dialog

2021-03-23 19:59 UTC, blackfalcon commented on src/depth.json
> +      "value": "{depth.400.value}",
@BrentLabasan have you had an opportunity to address this?

2021-03-29 16:26 UTC, BrentLabasan commented
@blackfalcon  In AuroDesignTokens dialog's depth was updated to a value of 400, and modal was updated to be listed as deprecated.

2021-03-30 18:20 UTC, blackfalcon commented
Closing PR in favor of https://github.com/AlaskaAirlines/AuroDesignTokens/pull/45

2021-03-30 18:20 UTC, closed without merging